// <auto-generated />
using Backend.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Backend.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Backend.Api.Models.Areas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Backend.Api.Models.Empleados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Apellidos")
                        .HasColumnType("text");

                    b.Property<int>("Documento")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .HasColumnType("text");

                    b.Property<int>("SubareasId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubareasId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Backend.Api.Models.Subareas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AreasId")
                        .HasColumnType("integer");

                    b.Property<string>("Subarea")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AreasId");

                    b.ToTable("Subareas");
                });

            modelBuilder.Entity("Backend.Api.Models.Empleados", b =>
                {
                    b.HasOne("Backend.Api.Models.Subareas", "Subarea")
                        .WithMany()
                        .HasForeignKey("SubareasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subarea");
                });

            modelBuilder.Entity("Backend.Api.Models.Subareas", b =>
                {
                    b.HasOne("Backend.Api.Models.Areas", "Area")
                        .WithMany()
                        .HasForeignKey("AreasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });
#pragma warning restore 612, 618
        }
    }
}
